version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    container_name: postgres-container
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $DB_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: .
    restart: unless-stopped
    container_name: nodejs-app-container
    env_file: .env
    ports:
      - $PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PSSWD=$POSTGRESDB_ROOT_PASSWORD
      - DB_DATABASE=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes:
  db: