image:
  repository: kaz01654/complete-devops-project
  tag: d3eacf3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

serviceAccount:
  enabled: false

autoscaling:
  enabled: false